# Generated by Django 6.0.4 on 2026-04-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('last_current_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_per_cost', models.DecimalField(decimal_places=2, default=7.0, help_text='Cost per electricity unit (₹)', max_digits=6)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, limit_choices_to={'role': 'tenant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_houses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'house',
                'ordering': ['house_number'],
            },
        ),
    ]
