# Generated by Django 6.0.4 on 2026-04-22 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0003_alter_house_options_alter_house_table_houselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
