# Generated by Django 6.0.4 on 2026-04-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_management', '0004_customuser_role_alter_house_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('tenant', 'Tenant')], max_length=40, null=True),
        ),
    ]
